#!/bin/sh
set -eu

PLUMOS_ROOT="${PLUMOS_ROOT:-/storage/plumos}"
RUN_ROOT="${PLUMOS_PORTMASTER_RUN_ROOT:-/run/plumos/portmaster}"
export PLUMOS_BUBBLE_PYTHON_EXTRA_LIBRARY_PATH="${RUN_ROOT}/lib"
exec "${PLUMOS_ROOT}/bin/plumos-python-bubble" "$@"
